name: Split Packages

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
        tags:
            - '*'
    workflow_dispatch: ~

jobs:
    split_monorepo:
        name: "Split packages"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    - { path: 'meta/cqrs-application-meta', name: 'cqrs-application-meta' }
                    - { path: 'meta/cqrs-infrastructure-meta', name: 'cqrs-infrastructure-meta' }
                    - { path: 'pack/cqrs-pack', name: 'cqrs-pack' }
                    - { path: 'meta/repository-domain-meta', name: 'repository-domain-meta' }
                    - { path: 'meta/repository-infrastructure-meta', name: 'repository-infrastructure-meta' }
                    - { path: 'pack/repository-pack', name: 'repository-pack' }
                    - { path: 'meta/security-domain-meta', name: 'security-domain-meta' }
                    - { path: 'meta/security-application-meta', name: 'security-application-meta' }
                    - { path: 'meta/security-infrastructure-meta', name: 'security-infrastructure-meta' }
                    - { path: 'pack/security-pack', name: 'security-pack' }
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Split of ${{ matrix.package.name }}
                uses: alphpaca/monoplus-split-action@2022.1-beta3
                with:
                    package_path: 'src/${{ matrix.package.path }}'
                    personal_access_token: ${{ secrets.MONOPLUS_PAT }}
                    git_username: 'loic425'
                    git_email: 'lc.fremont@gmail.com'
                    repository_owner: "monofony"
                    repository_name: "${{ matrix.package.name }}"
